orbs:
  codecov: codecov/codecov@4.0.1

version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - persist_to_workspace:
          root: target
          paths:
            - jacoco.exec
      # Upload to Codecov
      - codecov/upload:
          file: target/jacoco.exec
          flags: unittests

workflows:
  sample:
    jobs:
      - build-and-test
